---
title: Jupyter Notebooks
description: Jupyter exercises
instructions: |
    <p>
        In this exercise you must follow instructions, fill in the notebook as required
        and submit a notebook file (.ipynb)
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: jupyter.ipynb

container:
  image: apluslms/grade-python:3.7-3.2.3-3.0
  mount: exercises/jupyter
  cmd: /exercise/run.sh